# Generated by Django 4.2.7 on 2025-10-02 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VQCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_timestamp', models.DateField(blank=True, null=True)),
                ('three_de_mo', models.CharField(blank=True, max_length=100, null=True)),
                ('uid', models.CharField(db_index=True, max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('ihc_mo', models.CharField(blank=True, max_length=100, null=True)),
                ('ihc', models.CharField(blank=True, max_length=200, null=True)),
                ('makenica', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor', models.CharField(choices=[('3DE TECH', '3DE TECH'), ('IHC', 'IHC'), ('MAKENICA', 'MAKENICA')], max_length=50)),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'ACCEPTED'), ('SCRAP', 'SCRAP'), ('WABI-SABI', 'WABI-SABI'), ('RT CONVERSION', 'RT CONVERSION')], default='', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('pcb_type', models.CharField(blank=True, max_length=100, null=True)),
                ('qc_person_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vqc_data',
                'indexes': [models.Index(fields=['uid'], name='vqc_data_uid_947bac_idx'), models.Index(fields=['vendor'], name='vqc_data_vendor_b93c80_idx'), models.Index(fields=['status'], name='vqc_data_status_dcd6b2_idx'), models.Index(fields=['logged_timestamp'], name='vqc_data_logged__f5a6d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mo_number', models.CharField(max_length=100)),
                ('uid', models.CharField(db_index=True, max_length=200, unique=True)),
                ('ring_status', models.CharField(blank=True, default='', max_length=50)),
                ('charger_status', models.CharField(blank=True, max_length=50, null=True)),
                ('charger_lot_details', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('vendor', models.CharField(choices=[('3DE TECH', '3DE TECH'), ('IHC', 'IHC'), ('MAKENICA', 'MAKENICA')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor_data',
                'indexes': [models.Index(fields=['uid'], name='vendor_data_uid_dcdfb9_idx'), models.Index(fields=['vendor'], name='vendor_data_vendor_247be1_idx'), models.Index(fields=['date'], name='vendor_data_date_67a8cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='MigrationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200)),
                ('table_name', models.CharField(max_length=100)),
                ('records_count', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('migration_mode', models.CharField(default='FAST', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'migration_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('mo_number', models.CharField(max_length=100)),
                ('uid', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'ACCEPTED'), ('WABI-SABI', 'WABI-SABI'), ('SCRAP', 'SCRAP'), ('RT CONVERSION', 'RT CONVERSION'), ('FUNCTIONAL BUT REJECTED', 'FUNCTIONAL BUT REJECTED')], default='', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('na_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pcb', models.CharField(blank=True, max_length=100, null=True)),
                ('qc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('qc_person', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ft_data',
                'indexes': [models.Index(fields=['uid'], name='ft_data_uid_a78606_idx'), models.Index(fields=['status'], name='ft_data_status_d5880a_idx'), models.Index(fields=['date'], name='ft_data_date_2108e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DuplicateSerialsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('table_name', models.CharField(max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('migration_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etl.migrationhistory')),
            ],
            options={
                'db_table': 'duplicate_serials_log',
            },
        ),
        migrations.CreateModel(
            name='ChargingStationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_timestamp', models.DateField()),
                ('uid', models.CharField(db_index=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('mac_id', models.CharField(blank=True, max_length=100, null=True)),
                ('polishing_qc_status', models.CharField(blank=True, max_length=50, null=True)),
                ('after_moulding_status', models.CharField(blank=True, max_length=50, null=True)),
                ('ioc_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'charging_station_data',
                'indexes': [models.Index(fields=['uid'], name='charging_st_uid_4b27da_idx'), models.Index(fields=['status'], name='charging_st_status_046cd5_idx'), models.Index(fields=['logged_timestamp'], name='charging_st_logged__a1c101_idx')],
            },
        ),
    ]
