# Generated by Django 4.2.7 on 2025-10-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstationdata',
            name='logged_timestamp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ftdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
