# Generated by Django 4.2.7 on 2025-10-02 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostgreSQLConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(default='5432', max_length=10)),
                ('database_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(default='NOT_TESTED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postgres_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'postgresql_configuration',
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_account_json', models.TextField(help_text='Google Service Account JSON content')),
                ('vendor_data_url', models.URLField(help_text='Vendor Data Google Sheet URL', max_length=500)),
                ('vqc_data_url', models.URLField(help_text='VQC Data Google Sheet URL (contains 3 sub-sheets)', max_length=500)),
                ('ft_data_url', models.URLField(help_text='FT Data Google Sheet URL', max_length=500)),
                ('cs_data_url', models.URLField(help_text='Charging Station Data Google Sheet URL', max_length=500)),
                ('vendor_spreadsheet_id', models.CharField(blank=True, max_length=200)),
                ('vqc_spreadsheet_id', models.CharField(blank=True, max_length=200)),
                ('ft_spreadsheet_id', models.CharField(blank=True, max_length=200)),
                ('cs_spreadsheet_id', models.CharField(blank=True, max_length=200)),
                ('vendor_range', models.CharField(default='Working!A:G', max_length=100)),
                ('vqc_3detech_range', models.CharField(default='3DE TECH!A:M', max_length=100)),
                ('vqc_ihc_range', models.CharField(default='IHC!A:M', max_length=100)),
                ('vqc_makenica_range', models.CharField(default='MAKENICA!A:M', max_length=100)),
                ('ft_range', models.CharField(default='Working!A:O', max_length=100)),
                ('cs_range', models.CharField(default='FINAL STATUS!A:I', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(default='NOT_TESTED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sheets_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_sheets_configuration',
            },
        ),
    ]
